/// Flutter icons MyIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData platform_apple__color_negative = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_clubhouse__color_negative = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_discord__color_negative = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_dribbble__color_negative = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_facebook__color_negative = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_figma__color_negative = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_github__color_negative = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_google__color_negative = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_instagram__color_negative = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_linkedin__color_negative = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_medium__color_negative = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_messenger__color_negative = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_pinterest__color_negative = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_reddit__color_negative = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_signal__color_negative = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_snapchat__color_negative = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_spotify__color_negative = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_telegram__color_negative = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_threads__color_negative = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_twitch__color_negative = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_tiktok__color_negative = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_vk__color_negative = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_whatsapp__color_negative = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_x__twitter___color_negative = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_tumblr__color_negative = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData platform_youtube__color_negative = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
